<?php

return [
    'com_funciona' => [
        'titol' => "Com funciona l'app?",
        'intro' => "La Cartilla del Pelegrí t'acompanya durant tota la caminada. Aquí tens tot el que has de saber:",
        'passos' => [
            ['icona' => 'bi bi-qr-code-scan', 'titol' => 'Check-in a cada parada', 'text' => "Quan arribis a una parada, introdueix el codi secret que et donaran o escaneja el codi QR. Així podràs validar que has passat per cada punt!"],
            ['icona' => 'bi bi-geo-alt', 'titol' => 'El teu mapa', 'text' => "El mapa mostra la teva posició en temps real i la de tots els participants. Els monitors el segueixen des de l'administració per garantir la seguretat de tothom."],
            ['icona' => 'bi bi-eye-slash', 'titol' => 'La teva privacitat', 'text' => "Pots activar o desactivar les actualitzacions de posició en temps real des del botó de la barra inferior. Recorda: l'última posició sempre es guarda per seguretat."],
            ['icona' => 'bi bi-trophy', 'titol' => 'Ranking i progrés', 'text' => "Ves mirant el teu progrés a la cartilla! Quan completis una parada, apareixerà marcada. També pots veure el ranking general des del botó corresponent."],
            ['icona' => 'bi bi-file-pdf', 'titol' => 'La teva cartilla PDF', 'text' => "Un cop tinguis alguna parada completada, pots descarregar la teva cartilla personalitzada en PDF des de les normes."],
        ],
    ],
    'etapes' => [
        ['tram' => 'Sant Cugat (Inici Ruta Llarga)', 'notes' => 'Enllaç: https://maps.app.goo.gl/3zmyGxZJvnJGdxt67', 'ruta' => 'llarga'],
        ['tram' => 'Sant Cugat ➜ Rubí', 'notes' => '1a parada (Rubí). https://maps.app.goo.gl/sx8pJV1YfRAuz8Lh6', 'ruta' => 'llarga'],
        ['tram' => 'Rubí ➜ Les Fonts de Terrassa', 'notes' => '2a parada (Les Fonts). Inici ruta curta. https://maps.app.goo.gl/Wxn4bZYAD9wFFx1m6', 'ruta' => 'ambdues'],
        ['tram' => 'Les Fonts ➜ Quatre Vents', 'notes' => '3a parada. https://maps.app.goo.gl/umuG3J52hVsLpjTw5', 'ruta' => 'ambdues'],
        ['tram' => 'Quatre Vents ➜ Can Cabassa', 'notes' => '4a parada. https://maps.app.goo.gl/gUE7vKqxAsq3VBsLA', 'ruta' => 'ambdues'],
        ['tram' => 'Can Cabassa ➜ Oasi', 'notes' => '5a parada. https://maps.app.goo.gl/X3wCE3uE9CdpJZ167', 'ruta' => 'ambdues'],
        ['tram' => 'Oasi ➜ Olesa', 'notes' => '6a parada (Olesa). https://maps.app.goo.gl/Pzx7AbGAyv1F9EX5A', 'ruta' => 'ambdues'],
        ['tram' => 'Olesa ➜ La Puda', 'notes' => '7a parada (La Puda). https://maps.app.goo.gl/Ws9EgYgiTm5JiDM7A', 'ruta' => 'ambdues'],
        ['tram' => 'La Puda ➜ Aeri', 'notes' => '8a parada (Aeri). https://maps.app.goo.gl/y9WowCuEPuQTCvVa7', 'ruta' => 'ambdues'],
        ['tram' => 'Aeri ➜ Monistrol', 'notes' => '9a parada (Monistrol). https://maps.app.goo.gl/pgPRHjcSa1tZR2Tt6', 'ruta' => 'ambdues'],
        ['tram' => 'Monistrol ➜ Montserrat', 'notes' => '10a parada (Montserrat!).', 'ruta' => 'ambdues'],
    ],
    'materials' => [
        'caminar' => [
            'Motxilla petita còmode',
            'Cantimplora petita',
            'Botes de muntanya',
            'Mitjons d’esport + recanvi',
            'Capelina',
            'Roba d’abric capa a capa',
            'Ulleres de sol i crema solar',
            'Got reutilitzable amb nom',
            'Buff i guants',
            'Cacao labial + cremes calor/vaselina',
            'Esmorzar i sopar',
            'Frontal + piles',
            'Pals i barret (optatiu)',
            'Targeta 3 zones (ruta curta)',
        ],
        'pernocta' => [
            'Sac de dormir i coixí',
            'Pijama + sabatilles',
            'Tovallola i necesser',
            'Mudes dissabte i diumenge',
            'Calçat còmode',
            'Dinar dissabte',
            'Motxilla extra a l’esplai divendres',
        ],
    ],
    'consells' => [
        'Fes esport lleuger les setmanes prèvies.',
        'No et tallis les ungles el dia abans.',
        'Porta sabates ja utilitzades i en bon estat.',
        'Dina carbohidrats i sopa lleuger però contundent.',
        'Assegura piles del frontal i descansa bé.',
        'Evita carregar massa pes.',
        'No oblidis caputxa per pluja i vent.',
    ],
    'normes' => [
        'generals' => [
            'Caminem en grup, sense adelantar el primer moni.',
            'Ningú queda enrere del/la monitor/a escombra.',
            'El ritme el marca el monitor de capçalera.',
            'Si cal parar, avisa immediatament a un moni.',
            'Fem cas als cotxes escombra en cada parada.',
        ],
        'adults' => [
            'Anem amb menors',
            'No podem fumar si estem amb el grup',
            'Recordem donar exemple sempre',
        ],
    ],
    'termos' => 'Necessitem termos amb llet, cafè o caldo per divendres a la tarda. Si pots aportar o omplir-ne, contacta amb la comissió.',
    'preguntes' => 'Tens dubtes? Escriu al contacte oficial que apareix al formulari o parla amb el teu moni de referència.',
];
